### ISSUE TITLE
How to get High Quality and Interactive Summary Xray Datasets?

### ISSUE THREAD

**Issue by WangRongsheng** [mbzuai-oryx/XrayGPT#1]
Hello,

Thank you for your wonderful work and I would like to ask you:

**How to get High Quality and Interactive Summary Xray Datasets?**

Maybe it can help us with some other work.

Thank you!

**Comment by Amshaker** [comment]
Hi @WangRongsheng ,

Thank you for your interest in our work.

The steps for getting the High quality and interactive summaries are described in this [Readme](https://github.com/mbzuai-oryx/XrayGPT/blob/main/README-DATASET.md)

The process has two steps:-
- The first step (pre-processing) is to remove the noise from the data and clean it.
- The second step is to use the capabilities of gpt-3.5-turbo to generate interactive and better-quality instruction set.

**Comment by WangRongsheng** [comment]
@Amshaker Thank you! I will try it!
