### ISSUE TITLE
The link to "curated radiology" is same as the "medical_healthcare"

### ISSUE THREAD

**Issue by Dragon-Wu** [mbzuai-oryx/XrayGPT#12]
Nice work!
As the paper said in curating high-quality data, the authors further refine the radiology reports. Can we access this dataset? I think the original MIMIC-CXR report seems inappropriate, especially the finding compared to the previous examination.

**Comment by Amshaker** [comment]
Hi @Dragon-Wu ,

Sure, you can download our pre-processed datasets from here: https://github.com/mbzuai-oryx/XrayGPT/blob/main/README-DATASET.md
