### ISSUE TITLE
Some questions about the XrayGPT dataset

### ISSUE THREAD

**Issue by WangRongsheng** [mbzuai-oryx/XrayGPT#3]
Thank you for your wonderful work - XrayGPT. I have some questions about XrayGPT that I have to ask you.

I have downloaded the openi annoatations file from https://mbzuaiac-my.sharepoint.com/:u:/g/personal/omkar_thawakar_mbzuai_ac_ae/EVYGprPyzdhOjFlQ2aNJbykBj49SwTGBYmC1uJ7TMswaVQ?e=qdqS8U .  And I've downloaded the openi PNG image file from https://openi.nlm.nih.gov/imgs/collections/NLMCXR_png.tgz .

However I found that the `image_id` field in `filter_cap.json` does not correspond to the PNG image name, what is the reason for this? How do I deal with this issue?

Or I wonder if I could just get these PNG images that match `filter_cap.json`, which would speed up our work.

**Comment by yukkai** [comment]
> Thank you for your wonderful work - XrayGPT. I have some questions about XrayGPT that I have to ask you.
> 
> I have downloaded the openi annoatations file from https://mbzuaiac-my.sharepoint.com/:u:/g/personal/omkar_thawakar_mbzuai_ac_ae/EVYGprPyzdhOjFlQ2aNJbykBj49SwTGBYmC1uJ7TMswaVQ?e=qdqS8U . And I've downloaded the openi PNG image file from https://openi.nlm.nih.gov/imgs/collections/NLMCXR_png.tgz .
> 
> However I found that the `image_id` field in `filter_cap.json` does not correspond to the PNG image name, what is the reason for this? How do I deal with this issue?
> 
> Or I wonder if I could just get these PNG images that match `filter_cap.json`, which would speed up our work.

Hi, have you resolved this problem?

**Comment by Amshaker** [comment]
Hi @WangRongsheng  @yukkai ,

I apologize for the late reply.

The `image ID` in `filter_cap.json` is the unique part of the full image name.

For instance, if one downloaded image with two views has names of : `CXR3_IM-1384-1001.png` and `CXR3_IM-1384-2001.png`, you will find them in `filter_cap.json` as `"image_id": "1384_1"`, and `"image_id": "1384_2"`, respectively.

I hope this answer make it clear now.

Best regards,
Abdelrahman.
