### ISSUE TITLE
pre-trained vicuna_weights

### ISSUE THREAD

**Issue by LilCong** [mbzuai-oryx/XrayGPT#4]
Hello, thank you for sharing your data and code, but I don't know if you missed the pre-trained vicuna_weights

**Comment by OmkarThawakar** [comment]
Hi @LilCong,

Thank you for pointing it out.

Please refer to the updated link of vicuna weights. 

Thanks,

**Comment by OmkarThawakar** [comment]
Closing this as vicuna weights url is updated.
