### ISSUE TITLE
Ask a question in another language?

### ISSUE THREAD

**Issue by WangRongsheng** [mbzuai-oryx/XrayGPT#5]
He kept answering me in English when I asked questions in the make it language. So what do you think about using other languages for training in fintune rather than pre-training the whole model?

**Comment by Amshaker** [comment]
Hi @WangRongsheng ,

The LLM is trained only in the English language. 

If you want to use another language, I think you have to (1) Fine-tune Vicuna on the radiology data but in the desired language. (2) Convert pur proposed instruction-set to the desired language and fine-tune the transformation layer.

Please let us know if you have more questions, and sorry for the late reply.

Best regards,
Abdelrahman.

**Comment by WangRongsheng** [comment]
@Amshaker Thank you! This has helped me a lot
