### ISSUE TITLE
您好，开始微调时加载完VisualGLM-6B，提示还需要加载ChatGLM-6B参数吗？如果加载是全部权重吗？

### ISSUE THREAD

**Issue by MCenyuan** [mbzuai-oryx/XrayGPT#8]
/root/autodl-tmp/XrayGLM/chatglm-6b tokenizer! Now you can get tokenizer() everywhere

其中ChatGLM-6B中的tokenizer()需要全部的权重吗？

**Comment by 2132660698** [comment]
你是不是记错项目了，你问的这个问题应该是https://github.com/WangRongsheng/XrayGLM

**Comment by MCenyuan** [comment]
是的，问错了
